server:
  port: 9527
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
  profiles:dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: zuul-gateway-9527
    prefer-ip-address: true
zuul:
  prefix: "/bxx" #从什么开头
  ignored-services: "*" #忽略
  routes:
    plat.serviceId: plat-service #服务提供者的服务名
    plat.path: /plat/**

---

server:
  port: 9528
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
  profiles:test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: zuul-gateway-9527
    prefer-ip-address: true
zuul:
  prefix: "/bxx" #从什么开头
  ignored-services: "*" #忽略
  routes:
    plat.serviceId: plat-service #服务提供者的服务名
    plat.path: /plat/**