spring:
  profiles:
    active: dev

---
server:
  port: 9527
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY-DEV
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: zuul-gateway-9527
    prefer-ip-address: true
zuul:
  prefix:  "/bxx" #从什么开头
  ignored-services: "*" #忽略
  routes:
    plat.serviceId: plat-service-dev #服务提供者的服务名
    plat.path: /plat/**
  routes:
    plat.serviceId: service-brand-dev #服务提供者的服务名
    plat.path: /brand/**

---

server:
  port: 9528
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY-TEST
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: zuul-gateway-9527
    prefer-ip-address: true
zuul:
  routes:
    plat.serviceId: plat-service-test #服务提供者的服务名
    plat.path: /plat/**
  routes:
    plat.serviceId: service-brand-test #服务提供者的服务名
    plat.path: /brand/**
  prefix: "/bxx" #从什么开头
  ignored-services: "*" #忽略
